DELETE FROM user_roles;
DELETE FROM users;
ALTER SEQUENCE global_seq RESTART WITH 100000;

INSERT INTO users (ID, NAME, PASSWORD) VALUES (1, 'admin', '$2a$12$SZPbH8xFbe91ZleXgXkap.sJJdTry4fue1AW49FCb6OCyHbFumXbS');
INSERT INTO users (ID, NAME, PASSWORD) VALUES (2, 'user', '$2a$12$.Y2ZaXAHUIOoAEcjPSAltefhAJzz5ZiJTPrBY71X4unAddtkIsiqO');

INSERT INTO user_roles (USER_ID, ROLE) VALUES (1, 'ROLE_ADMIN');
INSERT INTO user_roles (USER_ID, ROLE) VALUES (2, 'ROLE_USER');